import { AbiItem } from 'web3-utils';

export const ABI_LLAMALEND_VAULT: AbiItem[] = [
  {
    anonymous: false,
    inputs: [{ indexed: false, name: 'max_supply', type: 'uint256' }],
    name: 'SetMaxSupply',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'sender', type: 'address' },
      { indexed: true, name: 'owner', type: 'address' },
      { indexed: false, name: 'assets', type: 'uint256' },
      { indexed: false, name: 'shares', type: 'uint256' },
    ],
    name: 'Deposit',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'sender', type: 'address' },
      { indexed: true, name: 'receiver', type: 'address' },
      { indexed: false, name: 'value', type: 'uint256' },
    ],
    name: 'Transfer',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'sender', type: 'address' },
      { indexed: true, name: 'receiver', type: 'address' },
      { indexed: true, name: 'owner', type: 'address' },
      { indexed: false, name: 'assets', type: 'uint256' },
      { indexed: false, name: 'shares', type: 'uint256' },
    ],
    name: 'Withdraw',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'owner', type: 'address' },
      { indexed: true, name: 'spender', type: 'address' },
      { indexed: false, name: 'value', type: 'uint256' },
    ],
    name: 'Approval',
    type: 'event',
  },
  {
    inputs: [],
    name: 'borrowed_token',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'collateral_token',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  { inputs: [], name: 'amm', outputs: [{ name: '', type: 'address' }], stateMutability: 'view', type: 'function' },
  {
    inputs: [],
    name: 'controller',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  { inputs: [], name: 'factory', outputs: [{ name: '', type: 'address' }], stateMutability: 'view', type: 'function' },
  {
    inputs: [
      { name: '_amm', type: 'address' },
      { name: '_controller', type: 'address' },
      { name: '_borrowed_token', type: 'address' },
      { name: '_collateral_token', type: 'address' },
    ],
    name: 'initialize',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: '_max_supply', type: 'uint256' }],
    name: 'set_max_supply',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'borrow_apr',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  { inputs: [], name: 'lend_apr', outputs: [{ name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
  { inputs: [], name: 'asset', outputs: [{ name: '', type: 'address' }], stateMutability: 'view', type: 'function' },
  {
    inputs: [],
    name: 'totalAssets',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'pricePerShare',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '_is_floor', type: 'bool' }],
    name: 'pricePerShare',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '_assets', type: 'uint256' }],
    name: 'convertToShares',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '_shares', type: 'uint256' }],
    name: 'convertToAssets',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '_receiver', type: 'address' }],
    name: 'maxDeposit',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '_assets', type: 'uint256' }],
    name: 'previewDeposit',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '_assets', type: 'uint256' }],
    name: 'deposit',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: '_assets', type: 'uint256' },
      { name: '_receiver', type: 'address' },
    ],
    name: 'deposit',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: '_receiver', type: 'address' }],
    name: 'maxMint',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '_shares', type: 'uint256' }],
    name: 'previewMint',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '_shares', type: 'uint256' }],
    name: 'mint',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: '_shares', type: 'uint256' },
      { name: '_receiver', type: 'address' },
    ],
    name: 'mint',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: '_owner', type: 'address' }],
    name: 'maxWithdraw',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '_assets', type: 'uint256' }],
    name: 'previewWithdraw',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '_assets', type: 'uint256' }],
    name: 'withdraw',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: '_assets', type: 'uint256' },
      { name: '_receiver', type: 'address' },
    ],
    name: 'withdraw',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: '_assets', type: 'uint256' },
      { name: '_receiver', type: 'address' },
      { name: '_owner', type: 'address' },
    ],
    name: 'withdraw',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: '_owner', type: 'address' }],
    name: 'maxRedeem',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '_shares', type: 'uint256' }],
    name: 'previewRedeem',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '_shares', type: 'uint256' }],
    name: 'redeem',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: '_shares', type: 'uint256' },
      { name: '_receiver', type: 'address' },
    ],
    name: 'redeem',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: '_shares', type: 'uint256' },
      { name: '_receiver', type: 'address' },
      { name: '_owner', type: 'address' },
    ],
    name: 'redeem',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: '_from', type: 'address' },
      { name: '_to', type: 'address' },
      { name: '_value', type: 'uint256' },
    ],
    name: 'transferFrom',
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: '_to', type: 'address' },
      { name: '_value', type: 'uint256' },
    ],
    name: 'transfer',
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: '_spender', type: 'address' },
      { name: '_value', type: 'uint256' },
    ],
    name: 'approve',
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: '_spender', type: 'address' },
      { name: '_add_value', type: 'uint256' },
    ],
    name: 'increaseAllowance',
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: '_spender', type: 'address' },
      { name: '_sub_value', type: 'uint256' },
    ],
    name: 'decreaseAllowance',
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  { inputs: [], name: 'admin', outputs: [{ name: '', type: 'address' }], stateMutability: 'view', type: 'function' },
  {
    inputs: [],
    name: 'maxSupply',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  { inputs: [], name: 'decimals', outputs: [{ name: '', type: 'uint8' }], stateMutability: 'view', type: 'function' },
  { inputs: [], name: 'name', outputs: [{ name: '', type: 'string' }], stateMutability: 'view', type: 'function' },
  { inputs: [], name: 'symbol', outputs: [{ name: '', type: 'string' }], stateMutability: 'view', type: 'function' },
  {
    inputs: [
      { name: 'arg0', type: 'address' },
      { name: 'arg1', type: 'address' },
    ],
    name: 'allowance',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'arg0', type: 'address' }],
    name: 'balanceOf',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalSupply',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
];

export const ABI_LLAMALEND_CONTROLLER: AbiItem[] = [
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'user', type: 'address' },
      { indexed: false, name: 'collateral', type: 'uint256' },
      { indexed: false, name: 'borrowed', type: 'uint256' },
      { indexed: false, name: 'debt', type: 'uint256' },
      { indexed: false, name: 'n1', type: 'int256' },
      { indexed: false, name: 'n2', type: 'int256' },
      { indexed: false, name: 'liquidation_discount', type: 'uint256' },
    ],
    name: 'UserState',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'caller', type: 'address' },
      { indexed: true, name: 'user', type: 'address' },
      { indexed: false, name: 'collateral_increase', type: 'uint256' },
      { indexed: false, name: 'loan_increase', type: 'uint256' },
    ],
    name: 'Borrow',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'caller', type: 'address' },
      { indexed: true, name: 'user', type: 'address' },
      { indexed: false, name: 'collateral_decrease', type: 'uint256' },
    ],
    name: 'RemoveCollateral',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'owner', type: 'address' },
      { indexed: true, name: 'spender', type: 'address' },
      { indexed: false, name: 'allow', type: 'bool' },
    ],
    name: 'Approval',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'caller', type: 'address' },
      { indexed: true, name: 'user', type: 'address' },
      { indexed: false, name: 'collateral_decrease', type: 'uint256' },
      { indexed: false, name: 'loan_decrease', type: 'uint256' },
    ],
    name: 'Repay',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'user', type: 'address' },
      { indexed: false, name: 'health', type: 'uint256' },
    ],
    name: 'SetExtraHealth',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'liquidator', type: 'address' },
      { indexed: true, name: 'user', type: 'address' },
      { indexed: false, name: 'collateral_received', type: 'uint256' },
      { indexed: false, name: 'borrowed_received', type: 'uint256' },
      { indexed: false, name: 'debt', type: 'uint256' },
    ],
    name: 'Liquidate',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: 'amount', type: 'uint256' }],
    name: 'CollectFees',
    type: 'event',
  },
  { inputs: [], name: 'MAX_RATE', outputs: [{ name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
  {
    inputs: [
      { name: '_collateral', type: 'uint256' },
      { name: '_debt', type: 'uint256' },
      { name: '_N', type: 'uint256' },
    ],
    name: 'create_loan',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: '_collateral', type: 'uint256' },
      { name: '_debt', type: 'uint256' },
      { name: '_N', type: 'uint256' },
      { name: '_for', type: 'address' },
    ],
    name: 'create_loan',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: '_collateral', type: 'uint256' },
      { name: '_debt', type: 'uint256' },
      { name: '_N', type: 'uint256' },
      { name: '_for', type: 'address' },
      { name: '_callbacker', type: 'address' },
    ],
    name: 'create_loan',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: '_collateral', type: 'uint256' },
      { name: '_debt', type: 'uint256' },
      { name: '_N', type: 'uint256' },
      { name: '_for', type: 'address' },
      { name: '_callbacker', type: 'address' },
      { name: '_calldata', type: 'bytes' },
    ],
    name: 'create_loan',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: '_collateral', type: 'uint256' },
      { name: '_debt', type: 'uint256' },
    ],
    name: 'borrow_more',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: '_collateral', type: 'uint256' },
      { name: '_debt', type: 'uint256' },
      { name: '_for', type: 'address' },
    ],
    name: 'borrow_more',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: '_collateral', type: 'uint256' },
      { name: '_debt', type: 'uint256' },
      { name: '_for', type: 'address' },
      { name: '_callbacker', type: 'address' },
    ],
    name: 'borrow_more',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: '_collateral', type: 'uint256' },
      { name: '_debt', type: 'uint256' },
      { name: '_for', type: 'address' },
      { name: '_callbacker', type: 'address' },
      { name: '_calldata', type: 'bytes' },
    ],
    name: 'borrow_more',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: '_collateral', type: 'uint256' }],
    name: 'add_collateral',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: '_collateral', type: 'uint256' },
      { name: '_for', type: 'address' },
    ],
    name: 'add_collateral',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: '_spender', type: 'address' },
      { name: '_allow', type: 'bool' },
    ],
    name: 'approve',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: '_collateral', type: 'uint256' }],
    name: 'remove_collateral',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: '_collateral', type: 'uint256' },
      { name: '_for', type: 'address' },
    ],
    name: 'remove_collateral',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: '_wallet_d_debt', type: 'uint256' }],
    name: 'repay',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: '_wallet_d_debt', type: 'uint256' },
      { name: '_for', type: 'address' },
    ],
    name: 'repay',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: '_wallet_d_debt', type: 'uint256' },
      { name: '_for', type: 'address' },
      { name: '_max_active_band', type: 'int256' },
    ],
    name: 'repay',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: '_wallet_d_debt', type: 'uint256' },
      { name: '_for', type: 'address' },
      { name: '_max_active_band', type: 'int256' },
      { name: '_callbacker', type: 'address' },
    ],
    name: 'repay',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: '_wallet_d_debt', type: 'uint256' },
      { name: '_for', type: 'address' },
      { name: '_max_active_band', type: 'int256' },
      { name: '_callbacker', type: 'address' },
      { name: '_calldata', type: 'bytes' },
    ],
    name: 'repay',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: '_wallet_d_debt', type: 'uint256' },
      { name: '_for', type: 'address' },
      { name: '_max_active_band', type: 'int256' },
      { name: '_callbacker', type: 'address' },
      { name: '_calldata', type: 'bytes' },
      { name: '_shrink', type: 'bool' },
    ],
    name: 'repay',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: '_value', type: 'uint256' }],
    name: 'set_extra_health',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: '_user', type: 'address' },
      { name: '_min_x', type: 'uint256' },
    ],
    name: 'liquidate',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: '_user', type: 'address' },
      { name: '_min_x', type: 'uint256' },
      { name: '_frac', type: 'uint256' },
    ],
    name: 'liquidate',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: '_user', type: 'address' },
      { name: '_min_x', type: 'uint256' },
      { name: '_frac', type: 'uint256' },
      { name: '_callbacker', type: 'address' },
    ],
    name: 'liquidate',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: '_user', type: 'address' },
      { name: '_min_x', type: 'uint256' },
      { name: '_frac', type: 'uint256' },
      { name: '_callbacker', type: 'address' },
      { name: '_calldata', type: 'bytes' },
    ],
    name: 'liquidate',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  { inputs: [], name: 'save_rate', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [],
    name: 'collect_fees',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  { inputs: [], name: 'amm', outputs: [{ name: '', type: 'address' }], stateMutability: 'view', type: 'function' },
  { inputs: [], name: 'view', outputs: [{ name: '', type: 'address' }], stateMutability: 'view', type: 'function' },
  { inputs: [], name: 'factory', outputs: [{ name: '', type: 'address' }], stateMutability: 'view', type: 'function' },
  {
    inputs: [],
    name: 'configurator',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'arg0', type: 'address' },
      { name: 'arg1', type: 'address' },
    ],
    name: 'approval',
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'borrowed_token',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: '_collateral', type: 'uint256' },
      { name: '_debt', type: 'uint256' },
      { name: '_N', type: 'uint256' },
    ],
    name: 'calculate_debt_n1',
    outputs: [{ name: '', type: 'int256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: '_collateral', type: 'uint256' },
      { name: '_debt', type: 'uint256' },
      { name: '_N', type: 'uint256' },
      { name: '_user', type: 'address' },
    ],
    name: 'calculate_debt_n1',
    outputs: [{ name: '', type: 'int256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'collateral_token',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '_user', type: 'address' }],
    name: 'debt',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'arg0', type: 'address' }],
    name: 'extra_health',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '_user', type: 'address' }],
    name: 'health',
    outputs: [{ name: '', type: 'int256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: '_user', type: 'address' },
      { name: '_full', type: 'bool' },
    ],
    name: 'health',
    outputs: [{ name: '', type: 'int256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: '_collateral', type: 'uint256' },
      { name: '_debt', type: 'uint256' },
      { name: '_N', type: 'uint256' },
      { name: '_for', type: 'address' },
      { name: '_full', type: 'bool' },
    ],
    name: 'create_loan_health_preview',
    outputs: [{ name: '', type: 'int256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: '_collateral', type: 'uint256' },
      { name: '_for', type: 'address' },
      { name: '_full', type: 'bool' },
    ],
    name: 'add_collateral_health_preview',
    outputs: [{ name: '', type: 'int256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: '_collateral', type: 'uint256' },
      { name: '_for', type: 'address' },
      { name: '_full', type: 'bool' },
    ],
    name: 'remove_collateral_health_preview',
    outputs: [{ name: '', type: 'int256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: '_collateral', type: 'uint256' },
      { name: '_debt', type: 'uint256' },
      { name: '_for', type: 'address' },
      { name: '_full', type: 'bool' },
    ],
    name: 'borrow_more_health_preview',
    outputs: [{ name: '', type: 'int256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: '_d_collateral', type: 'uint256' },
      { name: '_d_debt', type: 'uint256' },
      { name: '_for', type: 'address' },
      { name: '_shrink', type: 'bool' },
      { name: '_full', type: 'bool' },
    ],
    name: 'repay_health_preview',
    outputs: [{ name: '', type: 'int256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: '_user', type: 'address' },
      { name: '_caller', type: 'address' },
      { name: '_frac', type: 'uint256' },
      { name: '_full', type: 'bool' },
    ],
    name: 'liquidate_health_preview',
    outputs: [{ name: '', type: 'int256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'liquidation_discount',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'arg0', type: 'address' }],
    name: 'liquidation_discounts',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'loan_discount',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '_user', type: 'address' }],
    name: 'loan_exists',
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'arg0', type: 'address' }],
    name: 'loan_ix',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'arg0', type: 'uint256' }],
    name: 'loans',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'monetary_policy',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  { inputs: [], name: 'n_loans', outputs: [{ name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
  {
    inputs: [{ name: '_user', type: 'address' }],
    name: 'tokens_to_liquidate',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: '_user', type: 'address' },
      { name: '_frac', type: 'uint256' },
    ],
    name: 'tokens_to_liquidate',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '_user', type: 'address' }],
    name: 'tokens_to_shrink',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: '_user', type: 'address' },
      { name: '_d_collateral', type: 'uint256' },
    ],
    name: 'tokens_to_shrink',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'total_debt',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'admin_fees',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'admin_percentage',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: '_loan_discount', type: 'uint256' },
      { name: '_liquidation_discount', type: 'uint256' },
      { name: '_monetary_policy', type: 'address' },
      { name: '_view_blueprint', type: 'address' },
      { name: '_fee', type: 'uint256' },
      { name: '_price_oracle', type: 'address' },
      { name: '_liquidity_mining_callback', type: 'address' },
    ],
    name: 'configure',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: '_user', type: 'address' }],
    name: 'user_prices',
    outputs: [{ name: '', type: 'uint256[2]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '_user', type: 'address' }],
    name: 'user_state',
    outputs: [{ name: '', type: 'uint256[4]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'users_to_liquidate',
    outputs: [
      {
        components: [
          { name: 'user', type: 'address' },
          { name: 'x', type: 'uint256' },
          { name: 'y', type: 'uint256' },
          { name: 'debt', type: 'uint256' },
          { name: 'health', type: 'int256' },
        ],
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '_from', type: 'uint256' }],
    name: 'users_to_liquidate',
    outputs: [
      {
        components: [
          { name: 'user', type: 'address' },
          { name: 'x', type: 'uint256' },
          { name: 'y', type: 'uint256' },
          { name: 'debt', type: 'uint256' },
          { name: 'health', type: 'int256' },
        ],
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: '_from', type: 'uint256' },
      { name: '_limit', type: 'uint256' },
    ],
    name: 'users_to_liquidate',
    outputs: [
      {
        components: [
          { name: 'user', type: 'address' },
          { name: 'x', type: 'uint256' },
          { name: 'y', type: 'uint256' },
          { name: 'debt', type: 'uint256' },
          { name: 'health', type: 'int256' },
        ],
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: '_debt', type: 'uint256' },
      { name: '_N', type: 'uint256' },
    ],
    name: 'min_collateral',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: '_debt', type: 'uint256' },
      { name: '_N', type: 'uint256' },
      { name: '_user', type: 'address' },
    ],
    name: 'min_collateral',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: '_d_collateral', type: 'uint256' },
      { name: '_N', type: 'uint256' },
    ],
    name: 'max_borrowable',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: '_d_collateral', type: 'uint256' },
      { name: '_N', type: 'uint256' },
      { name: '_user', type: 'address' },
    ],
    name: 'max_borrowable',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'available_balance',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  { inputs: [], name: 'vault', outputs: [{ name: '', type: 'address' }], stateMutability: 'view', type: 'function' },
  { inputs: [], name: 'version', outputs: [{ name: '', type: 'string' }], stateMutability: 'view', type: 'function' },
  {
    inputs: [
      { name: '_borrow_cap', type: 'uint256' },
      { name: '_admin_percentage', type: 'uint256' },
    ],
    name: 'configure_lend',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: '_amount', type: 'uint256' }],
    name: 'on_borrowed_token_transfer_in',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: '_amount', type: 'uint256' }],
    name: 'on_borrowed_token_transfer_out',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: '_total_debt', type: 'uint256' }],
    name: '_on_debt_increased',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  { inputs: [], name: 'lent', outputs: [{ name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
  { inputs: [], name: 'repaid', outputs: [{ name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
  {
    inputs: [],
    name: 'collected',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'borrow_cap',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: '_vault', type: 'address' },
      { name: '_amm', type: 'address' },
      { name: '_borrowed_token', type: 'address' },
      { name: '_collateral_token', type: 'address' },
      { name: '_monetary_policy', type: 'address' },
      { name: '_loan_discount', type: 'uint256' },
      { name: '_liquidation_discount', type: 'uint256' },
      { name: '_view_blueprint', type: 'address' },
      { name: '_configurator', type: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
];

export const ABI_LLAMALEND_AMM: AbiItem[] = [
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'provider', type: 'address' },
      { indexed: false, name: 'amount', type: 'uint256' },
      { indexed: false, name: 'n1', type: 'int256' },
      { indexed: false, name: 'n2', type: 'int256' },
    ],
    name: 'Deposit',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'provider', type: 'address' },
      { indexed: false, name: 'amount_borrowed', type: 'uint256' },
      { indexed: false, name: 'amount_collateral', type: 'uint256' },
    ],
    name: 'Withdraw',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'buyer', type: 'address' },
      { indexed: false, name: 'sold_id', type: 'uint256' },
      { indexed: false, name: 'tokens_sold', type: 'uint256' },
      { indexed: false, name: 'bought_id', type: 'uint256' },
      { indexed: false, name: 'tokens_bought', type: 'uint256' },
    ],
    name: 'TokenExchange',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: 'rate', type: 'uint256' },
      { indexed: false, name: 'rate_mul', type: 'uint256' },
      { indexed: false, name: 'time', type: 'uint256' },
    ],
    name: 'SetRate',
    type: 'event',
  },
  {
    inputs: [],
    name: 'price_oracle_contract',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'liquidity_mining_callback',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '_admin', type: 'address' }],
    name: 'set_admin',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: 'i', type: 'uint256' }],
    name: 'coins',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'price_oracle',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'get_rate_mul',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'get_base_price',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'n', type: 'int256' }],
    name: 'p_current_up',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'n', type: 'int256' }],
    name: 'p_current_down',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'n', type: 'int256' }],
    name: 'p_oracle_up',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'n', type: 'int256' }],
    name: 'p_oracle_down',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  { inputs: [], name: 'get_p', outputs: [{ name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
  {
    inputs: [{ name: 'user', type: 'address' }],
    name: 'read_user_tick_numbers',
    outputs: [{ name: '', type: 'int256[2]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'user', type: 'address' }],
    name: 'read_user_ticks',
    outputs: [{ name: '', type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'n_end', type: 'int256' }],
    name: 'can_skip_bands',
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'active_band_with_skip',
    outputs: [{ name: '', type: 'int256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'user', type: 'address' }],
    name: 'has_liquidity',
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'user', type: 'address' },
      { name: 'amount', type: 'uint256' },
      { name: 'n1', type: 'int256' },
      { name: 'n2', type: 'int256' },
    ],
    name: 'deposit_range',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: 'user', type: 'address' },
      { name: 'frac', type: 'uint256' },
    ],
    name: 'withdraw',
    outputs: [{ name: '', type: 'uint256[2]' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: 'i', type: 'uint256' },
      { name: 'j', type: 'uint256' },
      { name: 'in_amount', type: 'uint256' },
    ],
    name: 'get_dy',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'i', type: 'uint256' },
      { name: 'j', type: 'uint256' },
      { name: 'in_amount', type: 'uint256' },
    ],
    name: 'get_dxdy',
    outputs: [
      { name: '', type: 'uint256' },
      { name: '', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'i', type: 'uint256' },
      { name: 'j', type: 'uint256' },
      { name: 'out_amount', type: 'uint256' },
    ],
    name: 'get_dx',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'i', type: 'uint256' },
      { name: 'j', type: 'uint256' },
      { name: 'out_amount', type: 'uint256' },
    ],
    name: 'get_dydx',
    outputs: [
      { name: '', type: 'uint256' },
      { name: '', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'i', type: 'uint256' },
      { name: 'j', type: 'uint256' },
      { name: 'in_amount', type: 'uint256' },
      { name: 'min_amount', type: 'uint256' },
    ],
    name: 'exchange',
    outputs: [{ name: '', type: 'uint256[2]' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: 'i', type: 'uint256' },
      { name: 'j', type: 'uint256' },
      { name: 'in_amount', type: 'uint256' },
      { name: 'min_amount', type: 'uint256' },
      { name: '_for', type: 'address' },
    ],
    name: 'exchange',
    outputs: [{ name: '', type: 'uint256[2]' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: 'i', type: 'uint256' },
      { name: 'j', type: 'uint256' },
      { name: 'out_amount', type: 'uint256' },
      { name: 'max_amount', type: 'uint256' },
    ],
    name: 'exchange_dy',
    outputs: [{ name: '', type: 'uint256[2]' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: 'i', type: 'uint256' },
      { name: 'j', type: 'uint256' },
      { name: 'out_amount', type: 'uint256' },
      { name: 'max_amount', type: 'uint256' },
      { name: '_for', type: 'address' },
    ],
    name: 'exchange_dy',
    outputs: [{ name: '', type: 'uint256[2]' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: 'user', type: 'address' }],
    name: 'get_y_up',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'user', type: 'address' }],
    name: 'get_x_down',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'user', type: 'address' }],
    name: 'get_sum_xy',
    outputs: [{ name: '', type: 'uint256[2]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'user', type: 'address' }],
    name: 'get_xy',
    outputs: [{ name: '', type: 'uint256[][2]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'p', type: 'uint256' }],
    name: 'get_amount_for_price',
    outputs: [
      { name: '', type: 'uint256' },
      { name: '', type: 'bool' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'rate', type: 'uint256' }],
    name: 'set_rate',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: 'fee', type: 'uint256' }],
    name: 'set_fee',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: 'liquidity_mining_callback', type: 'address' }],
    name: 'set_callback',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: '_price_oracle', type: 'address' }],
    name: 'set_price_oracle',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  { inputs: [], name: 'admin', outputs: [{ name: '', type: 'address' }], stateMutability: 'view', type: 'function' },
  { inputs: [], name: 'A', outputs: [{ name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
  { inputs: [], name: 'fee', outputs: [{ name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
  { inputs: [], name: 'rate', outputs: [{ name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
  {
    inputs: [],
    name: 'active_band',
    outputs: [{ name: '', type: 'int256' }],
    stateMutability: 'view',
    type: 'function',
  },
  { inputs: [], name: 'min_band', outputs: [{ name: '', type: 'int256' }], stateMutability: 'view', type: 'function' },
  { inputs: [], name: 'max_band', outputs: [{ name: '', type: 'int256' }], stateMutability: 'view', type: 'function' },
  {
    inputs: [{ name: 'arg0', type: 'int256' }],
    name: 'bands_x',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'arg0', type: 'int256' }],
    name: 'bands_y',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: '_borrowed_token', type: 'address' },
      { name: '_borrowed_precision', type: 'uint256' },
      { name: '_collateral_token', type: 'address' },
      { name: '_collateral_precision', type: 'uint256' },
      { name: '_A', type: 'uint256' },
      { name: '_sqrt_band_ratio', type: 'uint256' },
      { name: '_log_A_ratio', type: 'int256' },
      { name: '_base_price', type: 'uint256' },
      { name: '_fee', type: 'uint256' },
      { name: '_admin_fee', type: 'uint256' },
      { name: '_price_oracle', type: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
];

export const ABI_LLAMALEND_FACTORY: AbiItem[] = [
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'blueprint_id', type: 'string' },
      { indexed: false, name: 'blueprint_address', type: 'address' },
    ],
    name: 'BlueprintSet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'previous_owner', type: 'address' },
      { indexed: true, name: 'new_owner', type: 'address' },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, name: 'fee_receiver', type: 'address' }],
    name: 'SetFeeReceiver',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'id', type: 'uint256' },
      { indexed: true, name: 'collateral_token', type: 'address' },
      { indexed: true, name: 'borrowed_token', type: 'address' },
      { indexed: false, name: 'vault', type: 'address' },
      { indexed: false, name: 'controller', type: 'address' },
      { indexed: false, name: 'amm', type: 'address' },
      { indexed: false, name: 'price_oracle', type: 'address' },
      { indexed: false, name: 'monetary_policy', type: 'address' },
    ],
    name: 'NewVault',
    type: 'event',
  },
  { anonymous: false, inputs: [{ indexed: false, name: 'account', type: 'address' }], name: 'Paused', type: 'event' },
  { anonymous: false, inputs: [{ indexed: false, name: 'account', type: 'address' }], name: 'Unpaused', type: 'event' },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'controller', type: 'address' },
      { indexed: false, name: 'fee_receiver', type: 'address' },
    ],
    name: 'SetCustomFeeReceiver',
    type: 'event',
  },
  {
    inputs: [{ name: 'new_owner', type: 'address' }],
    name: 'transfer_ownership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  { inputs: [], name: 'paused', outputs: [{ name: '', type: 'bool' }], stateMutability: 'view', type: 'function' },
  { inputs: [], name: 'version', outputs: [{ name: '', type: 'string' }], stateMutability: 'view', type: 'function' },
  {
    inputs: [
      { name: '_borrowed_token', type: 'address' },
      { name: '_collateral_token', type: 'address' },
      { name: '_A', type: 'uint256' },
      { name: '_fee', type: 'uint256' },
      { name: '_loan_discount', type: 'uint256' },
      { name: '_liquidation_discount', type: 'uint256' },
      { name: '_price_oracle', type: 'address' },
      { name: '_monetary_policy', type: 'address' },
      { name: '_supply_limit', type: 'uint256' },
    ],
    name: 'create',
    outputs: [{ name: '', type: 'address[3]' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: '_n', type: 'uint256' }],
    name: 'markets',
    outputs: [
      {
        components: [
          { name: 'vault', type: 'address' },
          { name: 'controller', type: 'address' },
          { name: 'amm', type: 'address' },
          { name: 'collateral_token', type: 'address' },
          { name: 'borrowed_token', type: 'address' },
          { name: 'price_oracle', type: 'address' },
          { name: 'monetary_policy', type: 'address' },
        ],
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '_vault', type: 'address' }],
    name: 'vaults_index',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'amm_blueprint',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'controller_blueprint',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'vault_blueprint',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'controller_view_blueprint',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  { inputs: [], name: 'admin', outputs: [{ name: '', type: 'address' }], stateMutability: 'view', type: 'function' },
  { inputs: [], name: 'pause', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [], name: 'unpause', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [],
    name: 'fee_receiver',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '_controller', type: 'address' }],
    name: 'fee_receiver',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: '_controller', type: 'address' },
      { name: '_fee_receiver', type: 'address' },
    ],
    name: 'set_custom_fee_receiver',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: '_fee_receiver', type: 'address' }],
    name: 'set_default_fee_receiver',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: '_vault_id', type: 'uint256' }],
    name: 'coins',
    outputs: [{ name: '', type: 'address[2]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'market_count',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  { inputs: [], name: 'MIN_A', outputs: [{ name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
  { inputs: [], name: 'MAX_A', outputs: [{ name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
  {
    inputs: [],
    name: 'default_fee_receiver',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'arg0', type: 'address' }],
    name: 'check_contract',
    outputs: [
      {
        components: [
          { name: 'market_index', type: 'uint256' },
          { name: 'contract_type', type: 'uint256' },
        ],
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: '_amm_blueprint', type: 'address' },
      { name: '_controller_blueprint', type: 'address' },
      { name: '_vault_blueprint', type: 'address' },
      { name: '_controller_view_blueprint', type: 'address' },
      { name: '_configurator', type: 'address' },
      { name: '_admin', type: 'address' },
      { name: '_fee_receiver', type: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
];
